
version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:

